name: Deploy Fake
run-name: Deploy Fake ${{ github.run_number }}
on:
  workflow_call:
    secrets:
      ambiente:
        required: true
        description: 'Ambiente de entrega'
    

jobs:
    Deploy-kubernetes:
        runs-on: ubuntu-latest
        steps:
          - name: Build imagem docker
            run: |
                echo "Deploy ambiente de ${{ secrets.ambiente }}.."
          - name: Curl deploy ambiente
            run: |
                echo ${{ secrets.ambiente }}