name: CD FAKE
run-name: Deploy Fake ${{ github.run_number }}
on:
  workflow_dispatch:
      inputs:
        AMBIENTE_DEPLOY:
          description: 'Ambiente de deploy'
          required: true
          type: choice
          default: homologacao
          options:
            - homologacao
            - producao


jobs:
    Deploy-fake:
        runs-on: ubuntu-latest
        environment: ${{ inputs.AMBIENTE_DEPLOY }}
        steps:
          - name: fake d edeploy ambiente
            run: |
                echo "Deploy ambiente de ${{ vars.AMBIENTE_DEPLOY }}.."
    teste-fake:
       runs-on: ubuntu-latest
       steps:
          - name: fake teste ambiente
            run: |
                echo "Teste ambiente de ${{ vars.AMBIENTE_DEPLOY }}.."          