name: CD FAKE
run-name: Deploy Fake ${{ github.run_number }}
on:
  workflow_call:


jobs:
    Deploy-fake:
        runs-on: ubuntu-latest
        steps:
          - name: fake d edeploy ambiente
            run: |
                echo "Deploy ambiente de ${{ vars.AMBIENTE_DEPLOY }}.."
          